In [3]:
import csv
with open("data.csv", "w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow(["Name", "Age", "City"])
    writer.writerow(["Prasi", "20", "Kakinada"])
    writer.writerow(["Sai", "21", "Hyderabad"])

In [4]:
import numpy as np

In [5]:
a=np.array([1,2,3,4])

In [6]:
print(a.ndim)

1


In [7]:
b=np.array([[1,2,3],[4,5,6]])

In [8]:
print(b.ndim)

2


In [9]:
c = np.array([[[1,2],[3,4],[5,6],[7,6]]])

In [10]:
print(c.ndim)

3


In [11]:
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 6]]]


In [12]:
print(a.shape)

(4,)


In [13]:
print(b.shape)

(2, 3)


In [14]:
print(c.shape)

(1, 4, 2)


# indexing and slicing

In [15]:
a = np.arange(10)
print(a[5])

5


In [16]:
a = np.diag([1,2,3])
print(a[2,2])

3


# slicing

In [17]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(a[1:8:2])

[1 3 5 7]


In [19]:
a = np.arange(10)
a[5:]=10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

# copies and viewing

In [20]:
a = np.arange(10)
b = a[::2]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [21]:
print(np.shares_memory(a,b))

True


In [22]:
b[0] = 10
print(a)
print(b)

[10  1  2  3  4  5  6  7  8  9]
[10  2  4  6  8]


In [27]:
a = np.arange(10)
b = a[::2].copy() #force a copy
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [29]:
print(np.shares_memory(a,b))

False


In [30]:
b[0] = 10
print(a)

[0 1 2 3 4 5 6 7 8 9]


# random number generator

In [31]:
a = np.random.randint(0,20,15)
print(a)

[ 8  0 18  3  6 10 19 11 11 17 18 13 15  7  1]


In [32]:
mask=(a%2==0)

In [33]:
mask_a = a[mask]
print(mask_a)

[ 8  0 18  6 10 18]


In [34]:
a[mask] = -1
print(a)

[-1 -1 -1  3 -1 -1 19 11 11 17 -1 13 15  7  1]


# Element wise operations

1. basic operations

In [36]:
a = np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [37]:
print(a**2)

[ 1  4  9 16]


# all arthematic operations element wise

In [38]:
b = np.ones(4) + 1  #[2 2 2 2]
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [39]:
print(a*b)

[2. 4. 6. 8.]


In [40]:
print(a-b)

[-1.  0.  1.  2.]


In [41]:
print(a+b)

[3. 4. 5. 6.]


In [42]:
c = np.diag([1,2,3,4])
print(c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [43]:
print(c*c)
print("************************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# comprassion operator

In [46]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([1,2,3,4])
print(np.array_equal(a,b))

False


In [48]:
print(np.array_equal(a,c))

True


# logical operator

In [50]:
a = np.array([1,0,1,0],dtype = "bool")
b = np.array([1,1,0,0],dtype = "bool")

In [51]:
print(np.logical_or(a,b))

[ True  True  True False]


In [53]:
print(np.logical_and(a,b))

[ True False False False]


# trigonometry/transcendental function

In [55]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [56]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [57]:
np.log(a)

C:\Users\HARSHAVARDINI\AppData\Local\Temp\ipykernel_22564\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])